[package]
name = "day_1"
version = "0.1.0"
edition = "2021"

panic = 'abort'

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
strum_macros = "0.23"

strum = { version = "0.23", features = ["derive"] }
